TileDB-Inc/conda-forge-nightly-controller

.github/workflows/tiledb-py.yml, .github/workflows/tiledb.yml, scripts/open-issue.sh
If one of the GitHub Actions workflows failed, open an Issue (or comment on existing open Issue)
To do prior to merge:
Limitations:
* This uses the same Issue label for each recipe. Given that these workflows are largely tinkering with recipes, they are likely to fail for the same reasons. And even if not, the extra complexity of multiple labels doesn't seem worth it. I can add the complexity if requested
cc: @shaunrd0 ,@ihnorton 
xref: #1
=> Open Issue if GitHub Actions workflows fail

.github/workflows/activity.yml
GitHub [automatically disables scheduled workflows](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) if there has been no activity in the repo in the last 60 days. Obviously this policy isn't ideal for repos like this whose primary purpose is scheduling activity in other repos. This workflow pushes an empty commit every month in order to (hopefully) prevent this. I'm not 100% this will be sufficient activity, but it appears to be working in another repo I have that includes auto-commits from workflows.
cc: @shaunrd0 ,@ihnorton 
xref: #1
=> Add scheduled workflow to simulate regular activity

.github/workflows/tiledb-py.yml, .github/workflows/tiledb.yml
There have been [several failures](https://dev.azure.com/TileDB-Inc/CI/_build?definitionId=5&_a=summary) recently which appear to be caused by the tiledb-py run starting before all tiledb jobs have completed. This PR pushes the trigger time for tiledb-py back by one hour, to 0400  UTC / 11 PM EST.
=> Update tiledb-py.yml start time

.github/workflows/delete-old-nightlies.yml, scripts/delete-old-nightlies.sh, scripts/delete-old-nightlies.yml
This GitHub Actions pipelines deletes old nightlies. It is set to run every Monday and remove all nightlies that were uploaded more than 7 days ago
Closes #5 
cc: @ihnorton @Shelnutt2
The following setup steps are required:
1. Go to https://anaconda.org/tiledb/settings/access and create a new API token with scope "Allow all API operations"
1. Create a [new repository secret](https://github.com/TileDB-Inc/conda-forge-nightly-controller/settings/secrets/actions) named `ANACONDA_TOKEN` and copy-paste the token
The script can be run locally, eg:
```sh
mamba env create --file scripts/delete-old-nightlies.yml
mamba activate delete-old-nightlies
export ANACONDA_TOKEN="<api-token>"
ACCOUNT=tiledb DAYS=7 SUBDIR=osx-arm64 scripts/delete-old-nightlies.sh
```
Or executed remotely using the …
=> Delete old nightlies

scripts/delete-old-nightlies.sh
Because the libtiledb nightlies have been failing (#7), there are currently no nightlies in the subdir linux-ppc64le. When `conda search` is unable to find any packages, it fails with exit code 1, causing the entire script to fail. This PR fixes the problem using `||` and exiting early if a subdir contains no nightlies to delete.
=> Exit early if a subdir has no nightlies to delete

.github/workflows/linux-py37.yml
This is my proposal for automating the Python 3.7 builds of TileDB-Py for linux-64. This nightly repo already has the SSH keys setup to push to tiledb-py-feedstock, so I decided to include the workflow here instead of making an entirely new repo, especially since this should only be needed for a few more months.
I have already created the branch [build-linux-64-py37](https://github.com/TileDB-Inc/tiledb-py-feedstock/tree/build-linux-64-py37). I configured the branch to 1) only build with Python 3.7 on linux-64, and 2) upload to "tiledb main". Thus this new workflow simply pulls the latest version of the `meta.yaml` from the upstream conda-forge/tiledb-feedstock, commits, and pushes to this dedicated Python 3.7 branch. I'm hoping to avoid rerendering, since that adds extra complexity.
The …
=> A temporary workflow to build tiledb-py with Python 3.7 on linux-64

.github/workflows/tiledb-py.yml, .github/workflows/tiledb.yml
conda-smithy checks if it is the latest version available, and since the job caches the conda env, it fails to rerender the feedstock every time there is a new conda-smithy release
Closes #18 
xref: #16
=> Always update conda-smithy for nightly job

.github/workflows/activity.yml, .github/workflows/check-azure-status.yml, .github/workflows/delete-old-nightlies.yml, .github/workflows/linux-py37.yml, .github/workflows/tiledb-py.yml, .github/workflows/tiledb.yml
I realized that by using the same label, `bug`, for Issues opened by failures of any of the pipelines would result in every pipeline writing to the same open Issue (since the `open-issue` action uses the label(s) to determine if it should open a new Issue or comment on an existing one).
I created a new label `scheduled` as well as one for each of the 6 pipelines ([labels](https://github.com/TileDB-Inc/conda-forge-nightly-controller/labels)). Thus an automated Issue opened by a failed workflow will have the labels `bug`, `scheduled`, and `<name-of-workflow>`. This allows a developer to still manually open an Issue with the labels `bug` and `<name-of-workflow>` to document a bug that needs fixed
=> Use unique labels to distinguish Issues for each pipeline

.github/workflows/check-azure-status.yml
Currently the azure status checks run in parallel. In the case where both tiledb-feedstock and tiledb-py-feedstock fail their nightly builds, this can result in two Issues being opened, eg #44 and #45. However, when tiledb-feedstock fails, this will always cause tiledb-py-feedstock to fail. Thus one Issue is preferred.
This PR updates the Azure status checks to run serially, so that the tiledb-py-feedstock failure will append to the new Issue instead of opening an independent one.
=> Check Azure status in serial to avoid duplicate Issues

scripts/tiledb/update-recipe.sh
Closes #49. Solution from @teo-tsirpanis in https://github.com/conda-forge/tiledb-feedstock/pull/234
I triggered a run on my internal branch. You can see [here](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/7906907583/job/21582779534#step:9:45) that libboost-devel is added to the host requirements of the recipe.
Theodore previously pushed directly to the [nightly-build branch](https://github.com/TileDB-Inc/tiledb-feedstock/commits/nightly-build/) to confirm this [fixes the build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=37909&view=results). Note that those commits will be overwritten when the nightly build runs tonight.
=> Add libboost-devel to libtiledb nightly recipe for 2.21

scripts/tiledb/update-recipe.sh
Reverts TileDB-Inc/conda-forge-nightly-controller#50
TileDB has removed the dependency to Boost (TileDB-Inc/TileDB#4731).
=> Revert "Add libboost-devel to libtiledb nightly recipe for 2.21"

scripts/rerender-feedstock.sh
Closes #55 #56 
conda-smithy 3.31.0 was marked as broken and 3.31.1 hasn't been merged yet
https://github.com/conda-forge/conda-smithy-feedstock/pull/278
https://github.com/conda-forge/conda-smithy-feedstock/pull/279
https://github.com/conda-forge/conda-smithy/issues/1847
https://github.com/conda-forge/conda-smithy/issues/1848
=> Prevent unnecessary rerendering failures when conda-smithy is updated

.github/workflows/tiledb-py.yml, .github/workflows/tiledb.yml
Closes #64 and #65
Caused by https://github.com/conda-forge/conda-smithy/issues/1866
Successful runs in branches (that don't push to feedstock): [TileDB](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/8300518088), [TileDB-Py](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/8300519257)
=> Install jsonschema for conda-smithy v3.32.0

.github/workflows/check-azure-status.yml
Companion to https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/104
I hadn't realized this would create unnecessary noise on forks because I have disabled Actions on my fork of conda-forge-nightly-controller.
=> Do not open Issue for failed Azure nightly build on a fork

scripts/tiledb/update-recipe.sh
Add azure-identity-cpp into dependencies
=> Add azure-identity-cpp to host requirements of nightly tiledb recipe

.github/workflows/tiledb-py.yml, scripts/check-azure-status.sh
cc: @ihnorton, @kounelisagis 
xref: #70, #72 
Currently we have a single list of assignees for any nightly failure of either tiledb-feedstock or tiledb-py-feedstock. The other assignee fields are for troubleshooting conda-related setup errors, ie not build errors
Note this change will take effect the next time a nightly build failure Issue is opened, ie after #69 is closed
=> Add kounelisagis to assignees for nightly Azure feedstock failures

scripts/tiledb/update-recipe.sh
=> Use vs2022 for windows builds

scripts/add-and-commit.sh
Follow-up to #71. Last night's [nightly build](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=38658&view=results) added azure-identity-cpp to the host requirements but didn't include the empty overlay port for vcpkg ([commit](https://github.com/TileDB-Inc/tiledb-feedstock/commit/0f977ab5551f665d338bb6a93b6134b37362a19d)), so it was built with vcpkg instead of relying on the conda-installed one:
```
azure-identity-cpp:x64-linux -> 1.6.0 -- $SRC_DIR/build/_deps/vcpkg-src/buildtrees/versioning_/versions/azure-identity-cpp/cb43628d1a08baa198ed4cdc7d317ed73ed3815f
```
This PR updates the scripts to commit any changes made to the feedstock repository (including new files), so that any potential future fixes will automatically be committed.
xref: #69
=> Commit all edited and new files for nightly builds

scripts/tiledb/update-recipe.sh
Closes #86 
xref: follow-up to #74
We previously bumped the Windows compiler to vs2022. However, due to recent changes in the conda-forge ecosystem (they've added a new pin for the C standard library), we need to also pin `c_stdlib_version` to 2022.
I confirmed this fixes the build by pushing directly to the [nightly-build](https://github.com/TileDB-Inc/tiledb-feedstock/commits/nightly-build/) branch. Below are the relevant commits and CI (note that the commits will be overwritten by tonight's nightly, but the links to specific commits should continue to work)
https://github.com/TileDB-Inc/tiledb-feedstock/commit/52cebe41d1d4e93d03a245769cb66e4d2fb86e7f
https://github.com/TileDB-Inc/tiledb-feedstock/commit/a40b10ccdfd3ce7406c87d1b2c5a75b5a3963d20 …
=> Set c_stdlib_version to match Windows compiler

.github/workflows/activity.yml, .github/workflows/check-azure-status.yml, .github/workflows/delete-old-nightlies.yml, .github/workflows/tiledb-py.yml, .github/workflows/tiledb.yml
GitHub is deprecating Node 16 actions. Starting in June they will require opting-in to Node 16 by specifying an env var in the worfklow file.
https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update actions to Node 20

scripts/tiledb/update-recipe.sh
Closes #98
Details in https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/98#issuecomment-2137687678
=> Remove temporary pr-4995.patch

scripts/tiledb/update-recipe.sh
Closes #100
This reverts commit 2cd189f4a5048d5e3281ed49090631dcf852ca21.
Needs to be merged after 2.24.0 update PR is merged upstream in https://github.com/conda-forge/tiledb-feedstock/pull/295
=> Revert "Remove temporary pr-4995.patch (#99)".

scripts/tiledb/update-recipe.sh
Due to upstream changes, the `lz4-fix.patch` can no longer be applied. Until the next feedstock update, we have to remove this for the nightly builds.
xref: https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/108#issuecomment-2236234946, #99
Note that this is currently the only remaining patch, which means that the `patches:` field in the recipe YAML will be empty. I confirmed on my fork that this doesn't cause a problem ([commit](https://github.com/jdblischak/tiledb-feedstock/commit/8b209013423d9e7b7880c6285863ae9a4bc835d5), [build](https://dev.azure.com/jdblischak/feedstock-builds/_build/results?buildId=889&view=results))
=> Remove lz4-fix.patch

scripts/tiledb/update-recipe.sh
I copied the code for #110 from #99, and thus of course made the exact same mistake that I had to fix last time in #103
I confirmed via a [manual run](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/10012244974) of my internal branch (required to have SSH keys) that the patch is deleted.
=> Fix patch removal code from #110

.github/workflows/tiledb-py.yml, run-local-tiledb-py.sh, scripts/tiledb-py/obtain-version.sh, scripts/tiledb-py/update-recipe.py, scripts/tiledb/update-recipe.sh
Upstream TileDB-Py has been migrated to scikit-build-core (https://github.com/TileDB-Inc/TileDB-Py/pull/1988). I applied the changes in https://github.com/conda-forge/tiledb-py-feedstock/pull/224 to the nightly feedstock build.
I verified both locally with `run-local-tiledb-py.sh` and via a [run](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/10046546164/job/27766225652#step:12:1) on an internal branch.
```sh
git -C tiledb-py-feedstock/ --no-pager diff recipe/
diff --git a/recipe/bld.bat b/recipe/bld.bat
index 60fd47[9](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/10046546164/job/27766225652#step:12:10)..ecc81ff 100644
--- a/recipe/bld.bat
+++ b/recipe/bld.bat
@@ -1,5 +1 @@
-set TILEDB_CONDA_BUILD=1
-
-"%PYTHON%" setup.py build_ext …
```
=> Migrate tiledb-py-feedstock to scikit-build-core

scripts/tiledb-py/update-recipe.py
In #114, I copied the jinja2 syntax from https://github.com/conda-forge/tiledb-py-feedstock/pull/224 into the build scripts (it was easier to use separate build scripts than to try and use separate `script` YAML fields with jinja2 preprocessing selectors). This broke the nightly feedstock builds (https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/108#issuecomment-2245528288). This PR updates the build scripts to use environment variables.
I tested locally and from an [internal branch](https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/108#issuecomment-2245528288).
```diff
Run git -C tiledb-py-feedstock/ --no-pager diff recipe/
diff --git a/recipe/bld.bat b/recipe/bld.bat
index 60fd47[9](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/r …
```
=> Use env vars in build scripts for scikit-build-core migration

scripts/tiledb-py/update-recipe.py
Closes #116
Closes #119 
This PR fixes the nightly-build by removing the `script` field in `meta.yaml` since this repo adds custom build scripts.
This mostly undoes the temporary patches for scikit-build-core (#114, #115, #116) now that the upstream feedstock has been migrated (https://github.com/conda-forge/tiledb-py-feedstock/pull/232).
However, I had to keep the code that creates custom build scripts for two reasons:
1. The duplicate `script` fields for `not win` and `win` don't survive the round-trip import and export of the YAML recipe
2. An additional build flag was recently added in #122 
This is fine for now. Longer-term I would like to address these by:
1. In tiledb-py-feedstock, revert to use `build.sh` and `bld.bat`. Using `script` directly in `meta.yaml` is a convenience, but …
=> Remove temporary code to migrate tiledb-py-feedstock to scikit-build-core

scripts/tiledb-py/update-recipe.py
I replaced `script` in `meta.yaml` with separate build scripts in order to make it easier to patch the build commands for the nightly builds. Now I need to remove the lines that previously deleted `script` because now they will throw a missing key error (confirmed locally with `run-local-tiledb-py.sh`)
cc: @dudoslav 
xref: https://github.com/conda-forge/tiledb-py-feedstock/pull/235, #114, #115, #122, #123
I manually triggered a [run](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/10373104224/job/28717423817#step:12:1) to confirm that the build scripts are still properly overwritten:
```diff
diff --git a/recipe/bld.bat b/recipe/bld.bat
index fa0b28a..c354431 100644
--- a/recipe/bld.bat
+++ b/recipe/bld.bat
@@ -1,6 +1 @@
-@echo on
-
-set …
```
=> No longer need to delete `script` from tiledb-py-feedstock recipe

.github/workflows/delete-old-nightlies.yml
**Motivation:** to free up storage space on anaconda.org by reducing the number of nightly binaries stored at any one time
Currently the pipeline to delete old nightlies more than 7 days old only runs on Monday. Thus at the beginning of the week, there are only 7 days worth of nightlies stored on anaconda.org. However, by Sunday there are 14 days worth. This PR increases the frequency to daily so that there is consistently only 7 days worth of nightlies stored at once.
=> Delete old nightlies every day

scripts/tiledb-py/update-recipe.py
In an effort to reduce both the CI and storage required for the nightly feedstock builds, I updated the tiledb-py-feedstock to only build the oldest and newest Python versions supported by conda-forge, currently 3.8 and 3.12, respectively.
I confirmed this works locally as well as in a manual run, which showed the [CI files for 3.9, 3.10, and 3.11 being deleted](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/10564818555/job/29268043740#step:15:33).
Note that this will require the occasional manual maintenance as the conda-forge global pin for Python/numpy are updated. This PR is based on https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/5ccbd396dc675580aff241f5b313e4b00a2ad9d6/recipe/conda_build_config.yaml#L764
=> Only build oldest and newest Python variants for nightly builds

scripts/tiledb/update-recipe.sh
Closes #111
The recently released TileDB 2.26 no longer includes the lz4 patch in its feedstock recipe
xref: https://github.com/conda-forge/tiledb-feedstock/issues/315, https://github.com/conda-forge/tiledb-feedstock/pull/344
=> No longer need to manually remove lz4 patch for 2.26

scripts/tiledb-py/update-recipe.py
Closes #140 
The recently merged https://github.com/conda-forge/tiledb-py-feedstock/pull/238 bumped tiledb-py-feedstock to 0.32.0, dropped the py38 variant, and migrated to numpy 2. This PR updates the subset of Python and numpy variants for the nightly builds, and also deletes the numpy2 migration file if it exists, since it breaks the rerendering when using a subset in `conda_build_config.yaml`.
xref: #132
Successful test run in https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/10865136719/job/30151246441
=> Fix tiledb-py-feedstock setup job after migration to numpy 2

scripts/tiledb-py/update-recipe.py
When investigating #151, I noticed that there are now 3 Python variants being tested in the nightly builds: py39, py312, and py313. This is because tiledb-py-feedstock was recently migrated to py313 in https://github.com/conda-forge/tiledb-py-feedstock/pull/246. Even though our nightly scripts request only py39 and py312, since the migration file exists, the [rerendering](https://github.com/TileDB-Inc/tiledb-py-feedstock/commit/258fff9165133ef292fc55951f3a94c8db332580) keeps the py313 build.
Following the strategy I started in #132, this PR updates the nightly feedstock builds to only test with py39 and py313.
Here is a [manual run](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/12123294573/job/33798449382) of my internal branch that demonstrates that with this …
=> Replace py312 with py313 for build with latest Python variant

scripts/tiledb-py/update-recipe.py
Follow-up to #154 
I had missed the fact that the conda-forge name for py313 was different than previous python versions (https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/151#issuecomment-2514842134)
Example workflow run: https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/12147347024/job/33873366473#step:12:46
=> Fix name of conda-forge py313

scripts/tiledb-py/update-recipe.py
This PR undoes my recent PRs #154 and #155. My goal was to reduce the CI resources by only building two versions of Python instead of 3. However, trying to manually build only py39 and py313 has proved challenging, and I've determined it's not worth the effort to continue troubleshooting. Once the [py313 conda-forge migration](https://conda-forge.org/status/migration/?name=python313) has finished, then I'll update this repo.
xref: https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/151#issuecomment-2517953846
Example run that demonstrates that only the CI files for py310 and py311 are deleted: https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/12164471665/job/33926203028#step:15:31
=> Allow py313 to be a third Python build

scripts/tiledb-py/update-recipe.py
Frustratingly mamba 2 only supports trailing globs for version specifications (https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/151#issuecomment-2514886465, https://github.com/mamba-org/mamba/issues/3601#issuecomment-2518353107), thus we can no longer use `tiledb *.YYYY_MM_DD` to force the installation of the latest nightly binary.
There is an upside though. This will always install the latest available from `tiledb/label/nightlies`, so even if the tiledb-feedstock nightly fails, we can still test tiledb-py-feedstock with the latest TileDB-Py against the most recently available tiledb nightly conda binary.
Example run: https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/12284772346/job/34281301031#step:12:87
```diff
-    - tiledb >=2.26.0,<2.27
+ …
```
=> Install latest tiledb from tiledb/label/nightlies (support mamba 2)

scripts/tiledb-py/update-recipe.py
Follow-up to #157 
**Diagnosis:** That PR updated the tiledb requirement to be `tiledb`. However, that had the unforeseen consequence of then using the conda-forge global pin in `.ci_support/`, which is currently 2.26 (https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/151#issuecomment-2540015895).
**Solution:** Mamba 2 can properly handle trailing globs in version specifications. Thus I updated the script to replace the tiledb requirement with `tiledb 2.*`. This means we won't have to update it if/until we release a 3.0.
**Demonstration:**
* Using `tiledb 2.*` in the nightly-build on my [fork](https://github.com/jdblischak/tiledb-py-feedstock/commit/194245b52e3aec4722c872a8288ead29e49b3d8b) properly installed the nightly tiledb `2.27.0.2024_12_12`. The jobs ultimately …
=> Specify latest tiledb using the pin 2.*

scripts/tiledb-py/update-recipe.py
Closes #162 
Successful build on my branch (https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/12657342326/job/35271878617):
* The key `is_python_min` was added to `conda_build_config.yaml` (it adds `'true'` and `'false'` instead of `true` and `false`, but I don't think this matters) (https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/12657342326/job/35271878617#step:12:53)
* And the successful rerendering deleted the py310 and py311 build variants (https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/12657342326/job/35271878617#step:15:30)
=> Define new zip key is_python_min when limiting python variants

scripts/update-channels.sh
While troubleshooting the tiledb-py-feedstock failures in #167, I realized that no tiledb-py nightly conda binaries have been uploaded in at least a week (since we delete any older than 7 days).
https://anaconda.org/tiledb/tiledb-py/files
Looking at last night's Azure build [log](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=41871&view=results), it says "The branch nightly-build is not configured to be uploaded"
I was initially puzzled since we haven't made any related modifications recently to hte tiledb-py-feedstock nightly builds, but I eventually figured it out. Two months ago I added `upload_on_branch: main` to tiledb-py-feedstock to prevent accidental uploads from internal branches (https://github.com/conda-forge/tiledb-py-feedstock/pull/250).
The fix is …
=> Always upload binaries from branch "nightly-build"

scripts/tiledb-py/update-recipe.py
This reverts commit f1ed56dd2536b96a1d58f4e46a8c7b36e3eb6baf.
Undo https://github.com/TileDB-Inc/conda-forge-nightly-controller/pull/195 now that https://github.com/conda-forge/tiledb-py-feedstock/pull/266 was merged upstream
manual test run: https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/16455924208
=> Revert "Pin pybind11 <3 for nightly tiledb-py-feedstock builds (#195)"
